SiteFinal/sitefinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.core.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SiteFinal/apps/core/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    foto = models.ImageField(upload_to="foto_perfil")
    status = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.nome
    
class Empresa(models.Model):
    razao_social = models.CharField(max_length=100)
    cnpj = models.PositiveIntegerField()

    def __str__(self):
        return self.razao_social

class Categoria(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
        return self.tipo

class Servico(models.Model):
    tipo_servico = models.CharField(max_length=100)
    valor_servico = models.DecimalField(decimal_places=2, max_digits=10)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tipo_servico

class OrdemServico(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    servico = models.ManyToManyField(Servico)
    data_servico = models.DateTimeField(auto_now_add=True)
    data_finalizacao = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(blank=True, null=True)

    def __str__(self):
        return "OS: " + self.id + " | " + self.cliente.nome


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    valor = models.DecimalField(decimal_places=7, max_digits=10)
    descricao = models.TextField(verbose_name="Descrição", null=True)

    def __str__(self):
        return self.nome

SiteFinal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charsert="UTF-8">
        <meta name="viewport" content="width-device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "style-formularios.css" %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    
    <body>
        {% block titulo %} {% endblock %}

        {% block conteudo %} {% endblock %}
    </body>
</html>

SiteFinal/templates/conf-excluir.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Confirmar exclusão</title>
    </head>
    <body>
        <h2>Confirmar exclusão</h2>

        <p>Você confirma a exclusão de: {{ valor }} ?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit">Confirmar</button>
            <a href="#" onclick="window.history.back()">
                <button type="button">Cancelar</button>
            </a>
        </form>
    </body>
</html>

SiteFinal/templates/form-categoria (origin) (2).html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "style-formularios.css" %}">
        <title>Formulário Categoria</title>
    </head>
    <body>
        <a href="{% url "pg_criar_servico" %}">
            <button>Voltar</button>
        </a>
        <h2>Formulário Categoria</h2>

        <form method="post">
            {% csrf_token %}
            <p>
            <label for="id_tipo">Tipo:</label>
            <input type="text" name="tipo" maxlength="100" required="" id="id_tipo" value="{{ categoria.tipo }}">  
            </p>
            <button type="submit">Salvar</button>
            <a href="{% url "pg_criar_servico" %}">
                <button type="button">Cancelar</button>
            </a>
        </form>

        <h2>Lista de Categorias</h2>

        {% for categoria in categorias %}
            <div class="card-formulario">
                <span>{{ categoria.tipo }}</span>
                <div class="btns_formulario">
                    <a href="{% url "pg_editar_categoria" categoria.id %}">
                        <span>Editar Categoria</span>
                    </a>
                    <a href="{% url "pg_excluir_categoria" categoria.id %}">
                        <span>Excluir Categoria</span>
                    </a>
                </div>
            </div>
        {% endfor %}

    </body>
</html>

SiteFinal/templates/form-categoria (origin).html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "style-formularios.css" %}">
        <title>Formulário Categoria</title>
    </head>
    <body>
        <a href="{% url "pg_criar_servico" %}">
            <button>Voltar</button>
        </a>
        <h2>Formulário Categoria</h2>

        <form method="post">
            {% csrf_token %}
            {{ form_categoria.as_p }}
            <button type="submit">Salvar</button>
            <a href="{% url "pg_criar_servico" %}">
                <button type="button">Cancelar</button>
            </a>
        </form>

        <h2>Lista de Categorias</h2>

        {% for categoria in categorias %}
            <div class="card-formulario">
                <span>{{ categoria.tipo }}</span>
                <div class="btns_formulario">
                    <a href="{% url "pg_editar_categoria" categoria.id %}">
                        <span>Editar Categoria</span>
                    </a>
                    <a href="{% url "pg_excluir_categoria" categoria.id %}">
                        <span>Excluir Categoria</span>
                    </a>
                </div>
            </div>
        {% endfor %}

    </body>
</html>

SiteFinal/templates/form-categoria.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    <a href="{% url "pg_inicial" %}">
        <button>Voltar</button>
    </a>

    <div class="container">
        <h2>Formulário Categoria</h2>
    </div>
{% endblock %}

{% block conteudo %}

    <div class="container">
        <form method="post" id="form_categoria">
            {% csrf_token %}
            <p>
                <label for="id_tipo">Tipo:</label>
                <input type="text" class="form-control" name="tipo" maxlength="100" required="" id="id_tipo" value="{{ categoria.tipo }}">  
            </p>

            <button type="submit" class="btn btn-primary" id="Salvar">Salvar</button>
            <a href="{% url "pg_criar_servico" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
            </a>
        </form>
    </div>

    <div class="container">
        <h2>Lista de Categorias</h2>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Opções</th>
                </tr>
            </thead>

            <tbody>
                {% for categoria in categorias %}
                    <tr>
                        <td>{{ categoria.id }}</td>
                        <td>{{ categoria.tipo }}</td>
                        <td>
                            <div class="btns_formulario">
                                <a href="{% url "pg_editar_categoria" categoria.id %}">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=86374&format=png&color=000000" width='35' height='35'>Editar Categoria</img>
                                    </div>
                                </a>

                                <a href="{% url "pg_excluir_categoria" categoria.id %}" onclick="return confirm('Deseja realmente excluir?')">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=67884&format=png&color=000000" width='35' height='35'>Excluir Categoria</img>
                                    </div>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static "js/validacoes_categoria.js" %}"></script>
{% endblock %}

SiteFinal/templates/form-cliente (origin2).html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "style-formularios.css" %}">
        <title>Formulário Cliente</title>
    </head>

    <body>
        <a href="{% url "pg_inicial" %}">
            <button>Voltar</button>
        </a>
        <h2>Formulário Cliente</h2>

        <form method="post" id='form_cliente'>
            {% csrf_token %}
            <p>
                <label for="id_cliente">Nome:</label>
                <input type="text" name="nome" maxlength="100"  id="nome" value="{{ cliente.nome}}">  
            </p>

            <p>
                <label for="id_cliente">Data de Nascimento:</label>
                <input type="date" name="data_nascimento" maxlength="100"  id="data_nascimento" value="{{ cliente.data_nascimento}}">  
            </p>
            
            <p>
                <label for="id_cliente">Foto:</label>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="foto">
                    <!--<button type="submit">Enviar</button>-->
                    <button type="submit">Salvar</button>
                    <a href="{% url "pg_inicial" %}">
                        <button type="button">Cancelar</button>
                    </a>
                </form>
            </p>
        </form>
        
        <h2>Lista de Clientes</h2>

        {% for cliente in clientes %}
            <div class="card-formulario">
                <img src="{{ cliente.foto.url }}" width="150" height="auto">
                <span>{{ cliente.nome }}</span>
                <span><b>Data nascimento:</b> {{ cliente.data_nascimento }}</span>
                <div class="btns_formulario">
                    <a href="{% url "pg_editar_cliente" cliente.id %}">
                        <span>Editar Cliente</span>
                    </a>
                    <a href="{% url "pg_excluir_cliente" cliente.id %}" onclick=" return confirm('Deseja realmente excluir?')">
                        <span>Excluir Cliente</span>
                    </a>
                </div>
            </div>
        {% endfor %}

    </body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/validacoes_cliente.js'%}"></script>
</html>

SiteFinal/templates/form-cliente.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    <a href="{% url "pg_inicial" %}">
        <button>Voltar</button>
    </a>

    <div class="container">
        <h2>Formulário Cliente</h2>
    </div>
{% endblock %}

{% block conteudo %}

    <div class="container">
        <form method="post" id='form_cliente' enctype="multipart/form-data"> 
            {% csrf_token %}

            <input type="hidden" name="status" value="{{ cliente.status }}">
            
            <p>
                <label for="id_cliente">Nome:</label>
                <input type="text" name="nome" maxlength="100"  id="nome" value="{{ cliente.nome }}">  
            </p>

            <p>
                <label for="id_cliente">Data de Nascimento:</label>
                <input type="date" name="data_nascimento" maxlength="100"  id="data_nascimento" value="{{ cliente.data_nascimento }}">  
            </p>
            
            <p>
                <label for="id_cliente">Foto:</label>
                <input type="file" name="foto"> 
            </p>

            <p>
                <img src="{{ foto }}">
            </p>

            {% if cliente %}
                <p>
                    <label for="status">Status:</label>
                    <select class="form-control" name="status" required="" id="status">
                        <option value="{{ cliente.status }}" selected="{{ cliente.status }}">
                            {% if cliente.status == 0 %}
                                <td>Ativo</td>
                            {% else %}
                                <td>Inativo</td>
                            {% endif %}
                        </option>
                        <option value="0">Ativo</option>
                        <option value="1">Inativo</option>
                    </select>
                </p>
            {% endif %}
            
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url "pg_criar_cliente" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
            </a>
        </form>
    </div>
    
    <div class="container">
        <h2>Lista de Clientes</h2>
    </div>

    <div class="container">
        <table class="table">    
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Foto Perfil</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">Status</th>
                    <th scope="col">Opções</th>
                </tr>
            </thead>

            <tbody>
                {% for cliente in clientes %}
                    <tr>
                        <th scope="row">{{ cliente.id }}</th>
                        <td>{{ cliente.foto }}</td>
                        <td>{{ cliente.nome }}</td>
                        <td>{{ cliente.data_nascimento }}</td>
                        {% if cliente.status == 0 %}
                            <td>Ativo</td>
                        {% else %}
                            <td>Inativo</td>
                        {% endif %}
                        <td>
                            <div class="btns_formulario">
                                <a href="{% url "pg_editar_cliente" cliente.id %}">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=86374&format=png&color=000000" width='35' height='35'>Editar Cliente</img>
                                    </div>
                                </a>

                                <a href="{% url "pg_excluir_cliente" cliente.id %}" onclick=" return confirm('Deseja realmente excluir?')">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=67884&format=png&color=000000" width='35' height='35'>Excluir Cliente</img>
                                    </div>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/validacoes_cliente.js'%}"></script>
{% endblock %}

SiteFinal/templates/form-empresa.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
        <a href="{% url "pg_inicial" %}">
            <button>Voltar</button>
        </a>

        <div class="container">
            <h2>Formulário Empresa</h2>
        </div>
{% endblock %}

{% block conteudo %}

    <div class="container">
        <form method="post" id="form_empresa">
            {% csrf_token %}
            <p>
                <label for="id_empresa">Razão Social:</label>
                <input type="text" name="razao_social" maxlength="100"  id="razao_social" value="{{ empresa.razao_social }}">  
            </p>

            <p>
                <label for="id_empresa">CNPJ:</label>
                <input type="text" name="cnpj" maxlength="100"  id="cnpj" value="{{ empresa.cnpj }}">  
            </p>

            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url "pg_inicial" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
            </a>
        </form>
    </div>
    
    <div class="container">
        <h2>Lista de Empresas</h2>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Razão Social</th>
                    <th scope="col">CNPJ</th>
                    <th scope="col">Opções</th>
                </tr>
            </thead>
            
            <tbody>
                {% for empresa in empresas %}
                    <tr>
                        <th scope="row">{{ empresa.id }}</th>
                        <td>{{ empresa.razao_social }}</td>
                        <td>{{ empresa.cnpj }}</td>
                        <td>
                            <div class="btns_formulario">
                                <a href="{% url "pg_editar_empresa" empresa.id %}">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=86374&format=png&color=000000" width='35' height='35'>Editar Empresa</img>
                                    </div>
                                </a>

                                <a href="{% url "pg_excluir_empresa" empresa.id %}" onclick="return confirm('Deseja realmente excluir?')">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=67884&format=png&color=000000" width='35' height='35'>Excluir Empresa</img>
                                    </div>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'js/validacoes_empresa.js'%}"></script>
{% endblock %}

SiteFinal/templates/form-ordemServico (origin).html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Formulário Ordem de Serviço</title>
    </head>

    <body>
        <a href="{% url "pg_inicial" %}">
            <button>Voltar</button>
        </a>

        <h2>Formulário Ordem de Serviço</h2>

        <form method="post">
            {% csrf_token %}
            <p>
                <label for="cliente_id">Cliente:</label>
                <select name="cliente_id" required="" id="cliente_id">
                    <option value="" selected=""></option>
                    {% for cliente in clientes %}
                        <option value="{{ cliente.id }}">{{ cliente.nome }}</option>
                    {% endfor %}
                </select>
            </p>

            <p>
                <label for="servico_id">Serviço:</label>
                <select name="servico_id" required="" id="servico_id">
                    <option value="" selected=""></option>
                    {% for servico in servicos %}
                        <option value="{{ servico.id }}">{{ servico.nome }}</option>
                    {% endfor %}
                </select>
            </p>

            <p>
                <label for='tipo'>Data:</label>
                <input type='date' name='tipo' maxlength='50' required='' id='date'></input> 
            </p>

            <button type="submit">Salvar</button>
            <a href="{% url "pg_inicial" %}">
                <button type="button">Cancelar</button>
            </a>
        </form>
    </body>
</html>

SiteFinal/templates/form-ordemservico.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    <a href="{% url "pg_inicial" %}">
        <button>Voltar</button>
    </a>
    <div class="container">
        <h2>Formulário Ordem de Serviços</h2>
    </div>
{% endblock %}

{% block conteudo %}

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="id_cliente">Cliente:</label>
                <select name="cliente_id" class="form-control" id="cliente_id">
                    <option value="" selected=""></option>
                    {% for cliente in clientes %}
                        <option value="{{ cliente.id }}">{{ cliente.nome }}</option>
                    {% endfor %}
                </select>
            </p>

            <p>
                <label for="id_servico">Serviço:</label>
                <select name="servico_id" class="form-control" required="" id="servico_id">
                    <option value="" selected=""></option>
                    {% for servico in servicos %}
                        <option value="{{ servico.id }}">{{ servico.tipo }}</option>
                    {% endfor %}
                </select>
            </p>

            <p>
                <label for="data_servico">Data do Serviço:</label>
                <input type="date" class="form-control" name="data_servico" maxlength="100" required="" id="data_servico">
            </p>

            <p>
                <label for="data_finalizacao">Data de Finalização:</label>
                <input type="date" class="form-control" name="data_finalizacao" maxlength="100" required="" id="data_finalizacao">
            </p>

            <p>
                <label for="status">Status:</label>
                <select class="form-control" name="status" required="" id="status">
                    <option value="0">Em Andamento</option>
                    <option value="1">Concluído</option>
                </select>
            </p>

            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url "pg_inicial" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
            </a>
        </form>
    </div>

    <div class="container">
        <h2>Lista de Ordem de Serviços</h2>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Serviço</th>
                    <th scope="col">Status</th>
                    <th scope="col">Data do Serviço</th>
                    <th scope="col">Data de Finalização</th>
                    <th scope="col">Opções</th>
                </tr>
            </thead>

            <tbody>
                {% for os in ordemServicos %}
                    <tr>
                        <th scope="row">{{ os.id }}</th>
                        <td>{{ os.cliente.nome }}</td>
                        <td>{{ os.servico.tipo }}</td>
                        {% if os.status == 0 %}
                        <td>Em Andamento</td>
                        {% else %}
                        <td>Concluído</td>
                        {% endif %}
                        <td>{{ os.data_servico }}</td>
                        <td>{{ os.data_finalizacao }}</td>
                        <td>
                            <div class="btns_formulario">
                                {% comment %} <a href="{% url "pg_editar_ordemservico" os.id %}"> {% endcomment %}
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=86374&format=png&color=000000" width='35' height='35'>Editar</img>
                                    </div>
                                </a>

                                <a href="{% url "pg_excluir_ordemservico" os.id %}" onclick="return confirm('Deseja realmente excluir?')">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=67884&format=png&color=000000" width='35' height='35'>Excluir</img>
                                    </div>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/validacoes.js'%}"></script>
{% endblock %}

SiteFinal/templates/form-produto (origin).html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "style-formularios.css" %}">
        <title>Formulário Produto</title>
    </head>
    <body>
        <a href="{% url "pg_inicial" %}">
            <button>Voltar</button>
        </a>
        <h2>Formulário Produto</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_produto.as_p }}
            <button type="submit">Salvar</button>
            <a href="{% url "pg_inicial" %}">
                <button type="button">Cancelar</button>
            </a>
        </form>

        <h2>Lista de Produtos</h2>

        {% for produto in produtos %}
            <div class="card-formulario">
                <span>{{ produto.nome }}</span>
                <span>{{ produto.valor }}</span>
                <span>{{ produto.descricao }}</span>
                <div class="btns_formulario">
                    <a href="{% url "pg_editar_produto" produto.id %}">
                        <span>Editar Produto</span>
                    </a>
                    <a href="{% url "pg_excluir_produto" produto.id %}">
                        <span>Excluir Produto</span>
                    </a>
                </div>
            </div>
        {% endfor %}

    </body>
</html>

SiteFinal/templates/form-servico.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    <a href="{% url "pg_inicial" %}">
        <button>Voltar</button>
    </a>
    
    <a href="{% url "pg_criar_categoria" %}">
        <button>+ Categoria</button>
    </a>

    <div class="container">
        <h2>Formulário Serviço</h2>
    </div>
{% endblock %}

{% block conteudo %}

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p> 
                <label for="tipo">Tipo servico:</label>
                <input type="text" class="form-control" name="tipo" maxlength="100" required="" id="tipo">
            </p>
                
            <p>
                <label for="valor">Valor servico:</label>
                <input type="number" class="form-control" name="valor" step="0.01" required="" id="valor">
            </p>
                
            <p>
                <label for="id_empresa">Empresa:</label>
                <select name="empresa_id" class="form-control" required="" id="empresa_id">
                    <option value="" selected=""></option>
                    {% for empresa in empresas %}
                        <option value="{{ empresa.id }}">{{ empresa.razao_social }}</option>
                    {% endfor %}
                </select>
            </p>
                
            <p>
                <label for="id_categoria">Categoria:</label>
                <select name="categoria_id" class="form-control" required="" id="categoria_id">
                    <option value="" selected=""></option>
                    {% for categoria in categorias %}
                        <option value="{{ categoria.id }}">{{ categoria.tipo }}</option>
                    {% endfor %}
                </select>
            </p>

            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url "pg_inicial" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
            </a>
        </form>
    </div>
    
    <div class="container">
        <h2>Lista de Serviços</h2>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope='col'>Tipo</th>
                    <th scope='col'>Valor</th>
                    <th scope='col'>Empresa</th>
                    <th scope='col'>Categoria</th>
                    <th scope="col">Opções</th>
                </tr>
            </thead>

            <tbody>
                {% for servico in servicos %}
                    <tr>
                        <td>{{ servico.tipo }}</td>
                        <td>R$ {{ servico.valor }}</td>
                        <td>{{ servico.empresa.razao_social }}</td>
                        <td>{{ servico.categoria.tipo }}</td>
                        <td>
                            <div class="btns_formulario">
                                <a href="{% url "pg_editar_servico" servico.id %}">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=86374&format=png&color=000000" width='35' height='35'>Editar Serviço</img>
                                    </div>
                                </a>
                                <a href="{% url "pg_excluir_servico" servico.id %}" onclick="return confirm('Deseja realmente excluir?')">
                                    <div>
                                        <img src="https://img.icons8.com/?size=100&id=67884&format=png&color=000000" width='35' height='35'>Excluir servico</img>
                                    </div>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}